apiVersion: apps/v1
kind: Deployment
metadata:
  name: neocustomermodel-deployment
spec:
  selector:
    matchLabels:
      app: neocustomermodel
  replicas: 1
  template:
    metadata:
      labels:
        app: neocustomermodel
    spec:
      containers:
      - name: neocustomermodel
        image: ml-model-serving-layer-0.0.1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
